services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      NEO4J_URI: bolt://db:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: 12345678
      NEO4J_DATABASE: neo4j
    depends_on:
      db:
        condition: service_healthy
  db:
    image: neo4j:5.23
    environment:
      NEO4J_AUTH: neo4j/12345678
      NEO4JLABS_PLUGINS: "[\"apoc\"]"
    volumes:
      - neo4j-data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: wget http://db:7474 || exit 1
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  neo4j-data:
